[package]
name = "blit"
version = "0.5.12"
edition = "2018"
authors = ["Thomas Versteeg <thomasversteeg@gmx.com>"]
license = "GPL-3.0"
homepage = "https://github.com/tversteeg/blit"

readme = "README.md"
description = "Blit sprites on a buffer with a mask"
documentation = "https://docs.rs/blit"

repository = "https://github.com/tversteeg/blit.git"
keywords = ["image", "gamedev", "sprite", "blitting"]
categories = ["games", "rendering::data-formats", "game-engines", "multimedia::images"]

[badges]
travis-ci = {repository = "tversteeg/blit"}

[features]
default = ["image", "aseprite"]

[dependencies]
rayon = "1.3.0"
bincode = "1.2.1"
serde = "1.0.104"
serde_derive = "1.0.104"
quick-error = "1.2.3"
num-traits = "0.2.11"
image = { version = "0.23.0", optional = true }
aseprite = { version = "0.1.3", optional = true }

[[bench]]
name = "benchmarks"
harness = false

[dev-dependencies]
image = "0.23.0"
minifb = "0.15.3"
serde_json = "1.0.48"
criterion = "0.3.1"
